server:
  port: 4004 # Gateway listens on port 4004

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://host.docker.internal:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # Route for /api/customers/** to customer-service
        - id: customer-service-route
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/api/customers/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # Route for /api/docs/customers to customer-service /v3/api-docs
        - id: api-docs-customer-route
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/api-docs/customers
          filters:
            - RewritePath=/api-docs/customers,/v3/api-docs

        - id: api-docs-auth-route
          uri: http:/host.docker.internal:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs
